[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000
verbosity = 2
solc_version = "0.8.13"
remappings = ['@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/']

[profile.ci]
verbosity = 3

[rpc_endpoints]
zerog = "https://evmrpc-testnet.0g.ai"

[etherscan]
zerog = { key = "verifytoken", url = "https://chainscan-newton.0g.ai/api" }
