[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000
verbosity = 2
# fuzz = { runs = 256 }
# invariant = { runs = 64, depth = 64, fail_on_revert = true }
solc_version = "0.8.13"

[profile.ci]
verbosity = 3
# fuzz = { runs = 2000 }
# invariant = { runs = 256, depth = 256, fail_on_revert = true }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
